services:
  surrealdb:
    image: ${SURREALDB_IMAGE:?SURREALDB_IMAGE is required}

    container_name: ${SURREALDB_CONTAINER_NAME:?SURREALDB_CONTAINER_NAME is required}

    command:
      - start
      - --log
      - ${SURREALDB_LOG_LEVEL:?SURREALDB_LOG_LEVEL is required}
      - --user
      - ${SURREALDB_USERNAME:?SURREALDB_USERNAME is required}
      - --pass
      - ${SURREALDB_PASSWORD:?SURREALDB_PASSWORD is required}
      - rocksdb:/data/database.db

    ports:
      - "${SURREALDB_HOST_PORT:?SURREALDB_HOST_PORT is required}:8000"

    volumes:
      - "${SURREALDB_DATA_DIR:?SURREALDB_DATA_DIR is required}:/data"

    restart: ${SURREALDB_RESTART_POLICY:?SURREALDB_RESTART_POLICY is required}